### ISSUE TITLE
Update please

### ISSUE THREAD

**Issue by dsiminiuk** [urbiworx/node-red-contrib-midi#14]
Any chance of this being updated to work on a current version of node-red?

**Comment by johnty** [comment]
looks like just updating the midi dependency to 2.0.0 works fine... (some basic testing shows it working with node.js v14 and node-red 2.1.3, in both OSX and Raspberry Pi)

I basically did this for a manual install:

1. clone this repo to `~/.node-red/node_modules` (i.e. into folder `~/.node-red/node_modules/node-red-contrib-midi`)
2. update the midi dependency to midi version 2.0.0 in [package.json](https://github.com/urbiworx/node-red-contrib-midi/blob/master/package.json#L6)
3. run `npm install`

**Comment by natcl** [comment]
I just updated to 2.0.0, let me know if it works, I'll close for now but re-open if you have an issue, thanks !
