### ISSUE TITLE
node-red-contrib-midi 1.1.2 on node-red Version: 3.0.2

### ISSUE THREAD

**Issue by BobStone23** [urbiworx/node-red-contrib-midi#18]
Hello all
Since the update of node-red to version 3.0.2 unfortunately the node-red-contrib-midi version does not work anymore. I can't install it anymore and need it for a school assignment.
Can someone help me further?

[node-red-contrib-midi_Error_Message.txt](https://github.com/urbiworx/node-red-contrib-midi/files/11066330/node-red-contrib-midi_Error_Message.txt)

**Comment by natcl** [comment]
It works fine for me on 3.0.2
What os are you trying to run it on and what version of node.js ?

**Comment by natcl** [comment]
Also make sure the `libasound2-dev` package is installed.

**Comment by BobStone23** [comment]
Hi natcl

root@raspberrypi:/etc# cat os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

root@raspberrypi:~# node
Welcome to Node.js v16.19.1.

Which version did you use?

![node-red-contrib-midi](https://user-images.githubusercontent.com/15955244/227632625-eb3401be-2c41-431d-ad00-6d55baa8cd41.png)

**Comment by BobStone23** [comment]
Thank you for pointing this out, everything worked fine.

![node-red-contrib-midi_](https://user-images.githubusercontent.com/15955244/227636946-8d30142b-f886-4c21-bbaa-7db3db8e8cf6.png)
